# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
inhibit_all_warnings!

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# MARK: - Targets
target 'KurozoraKit_Tests' do
  pod 'KurozoraKit', :path => '../'
end

# MARK: - Post install scripts
post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
		end
	end
end
