source 'https://github.com/kiritokatklian/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
inhibit_all_warnings!

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# MARK: - Targets
target 'KurozoraKit_Tests' do
  pod 'KurozoraKit', :path => '../'

  pod 'KeychainAccess'
  pod 'Kingfisher'
  pod 'SCLAlertView', '~> 0.8'
  pod 'TRON'
  pod 'TRON/SwiftyJSON'
end
