author: "Khoren Katklian"
author_url: "https://kurozora.app"
copyright: "Copyright © 2018-present Khoren Katklian. All rights reserved. See [license](https://github.com/kiritokatklian/KurozoraKit/blob/master/LICENSE)."
readme: README.md

module: KurozoraKit
module_version: 0.4.1

github_url: "https://github.com/kiritokatklian/KurozoraKit"
github_file_prefix: "https://github.com/kiritokatklian/KurozoraKit/tree/master"

root_url: "https://kiritokatklian.github.io/KurozoraKit/"
docset_icon: ".github/Assets/KurozoraKit_icon.png"
dash_url: "https://kiritokatklian.github.io/KurozoraKit/docsets/KurozoraKit.xml"

clean: true
min_acl: internal
skip_undocumented: true

podspec: "KurozoraKit.podspec"
