//
//  TwoFactorChallengeRequest.swift
//  KurozoraKit
//
//  Created by Khoren Katklian on 28/04/2026.
//  MIT License
//

import Foundation

/// A request that resolves a two-factor authentication challenge issued by ``SignInRequest``.
///
/// Configure the request with either a TOTP code through ``otp(_:)`` or a
/// recovery code through ``recoveryCode(_:)`` before calling ``response()``.
/// Calling ``response()`` without a configured credential, or with both,
/// throws an ``APIError`` synchronously, without performing a network request.
public struct TwoFactorChallengeRequest: Sendable {
	// MARK: - Properties
	/// The request context that carries the configuration shared with the
	/// originating ``KurozoraKit`` instance.
	private let context: RequestContext

	/// The short-lived challenge token to redeem.
	private let challengeToken: String

	/// The TOTP code configured through ``otp(_:)``, if any.
	private var totpCode: String?

	/// The recovery code configured through ``recoveryCode(_:)``, if any.
	private var recoveryCode: String?

	// MARK: - Initializers
	/// Creates a request that resolves the specified two-factor challenge.
	///
	/// - Parameters:
	///   - context: The request context that carries the configuration shared
	///     with the originating ``KurozoraKit`` instance.
	///   - challengeToken: The short-lived challenge token issued by ``SignInRequest``.
	internal init(context: RequestContext, challengeToken: String) {
		self.context = context
		self.challengeToken = challengeToken
		self.totpCode = nil
		self.recoveryCode = nil
	}

	// MARK: - Builders
	/// Returns a copy of the request configured to resolve the challenge with
	/// a six-digit TOTP code from the user's authenticator app.
	///
	/// Mutually exclusive with ``recoveryCode(_:)``; the most recently
	/// configured credential takes effect.
	///
	/// - Parameter code: The six-digit TOTP code generated by the user's authenticator app.
	/// - Returns: A copy of the request configured with the TOTP code.
	public func otp(_ code: String) -> Self {
		var copy = self
		copy.totpCode = code
		copy.recoveryCode = nil
		return copy
	}

	/// Returns a copy of the request configured to resolve the challenge with
	/// a single-use recovery code generated during two-factor enrollment.
	///
	/// Mutually exclusive with ``otp(_:)``; the most recently configured
	/// credential takes effect.
	///
	/// - Parameter code: A single-use recovery code generated during two-factor enrollment.
	/// - Returns: A copy of the request configured with the recovery code.
	public func recoveryCode(_ code: String) -> Self {
		var copy = self
		copy.recoveryCode = code
		copy.totpCode = nil
		return copy
	}

	// MARK: - Execution
	/// Performs the request and returns the signed-in user on success.
	///
	/// On success the session is recorded against the originating
	/// ``KurozoraKit`` instance, mirroring the non-two-factor sign-in path.
	///
	/// - Returns: A ``SignInResponse`` describing the authenticated session.
	/// - Throws: An ``APIError`` if no credential is configured, if both
	///   credentials are configured, or if the request itself fails.
	@MainActor
	public func response() async throws -> SignInResponse {
		var parameters: [String: Any] = [
			"challenge_token": self.challengeToken
		]

		switch (self.totpCode, self.recoveryCode) {
		case (let code?, nil):
			parameters["otp"] = code
		case (nil, let code?):
			parameters["recovery_code"] = code
		case (nil, nil):
			throw APIError(
				message: "A TOTP code or recovery code is required to complete the two-factor challenge.",
				response: nil,
				request: nil
			)
		case (_?, _?):
			throw APIError(
				message: "Provide either a TOTP code or a recovery code, not both.",
				response: nil,
				request: nil
			)
		}

		let request = KKRequest<SignInResponse>(
			path: KKEndpoint.Users.twoFactorChallenge.endpointValue,
			method: .post,
			headers: self.context.headers,
			body: .formURLEncoded(parameters)
		)
		let response = try await self.context.client.send(request)
		self.context.applySignIn(token: response.authenticationToken, user: response.data.first)
		return response
	}
}
